import React from "react";
const { useState, useEffect, useCallback } = React;
import { C, SH, brl } from "../constants.js";
import { Header, Centro, Stat, SectionTitle } from "../ui.jsx";
import { sb } from "../db.js";

const S = {
  card:{background:C.card,border:"1px solid "+C.line,borderRadius:14,padding:16,boxShadow:SH},
  input:{padding:"9px 10px",border:"1px solid "+C.line,borderRadius:8,background:C.paper,color:C.ink,minWidth:130},
  btn:{padding:"9px 14px",border:0,borderRadius:8,background:C.brand,color:"#fff",fontWeight:700,cursor:"pointer"},
  th:{padding:"9px 10px",textAlign:"left",fontSize:11,textTransform:"uppercase",color:C.muted,borderBottom:"1px solid "+C.line},
  td:{padding:"9px 10px",fontSize:13,borderBottom:"1px solid "+C.line,verticalAlign:"top"},
};
const hoje=()=>new Date().toISOString().slice(0,10);
const num=n=>Number(n||0).toLocaleString("pt-BR",{maximumFractionDigits:2});
const ok=async p=>{const {data,error}=await p;if(error)throw error;return data};
const listar=t=>ok(sb.from(t).select("*").order("criado_em",{ascending:false}));
const inserir=(t,v)=>ok(sb.from(t).insert(v).select().single());
const atualizar=(t,id,v)=>ok(sb.from(t).update(v).eq("id",id).select().single());
const csv=(nome,rows)=>{
  const esc=v=>'"'+String(v??"").replace(/"/g,'""')+'"';
  const blob=new Blob([rows.map(r=>r.map(esc).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});
  const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=nome;a.click();URL.revokeObjectURL(a.href);
};
function Campo({label,children}){return <label style={{display:"flex",flexDirection:"column",gap:5,fontSize:12,color:C.muted}}>{label}{children}</label>}
function Tabela({cols,rows,vazio="Nenhum registro."}){return <div style={{overflow:"auto",...S.card,padding:0}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:650}}><thead><tr>{cols.map(c=><th key={c[0]} style={S.th}>{c[1]}</th>)}</tr></thead><tbody>{!rows.length&&<tr><td colSpan={cols.length} style={S.td}>{vazio}</td></tr>}{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c[0]} style={S.td}>{c[2]?c[2](r):r[c[0]]}</td>)}</tr>)}</tbody></table></div>}
function Form({children,onSubmit,label="Salvar"}){return <form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget),e.currentTarget)}} style={{...S.card,display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}>{children}<button style={S.btn}>{label}</button></form>}
function Erro({msg}){return msg&&<div style={{padding:10,background:"#FBEAE3",color:C.clay,borderRadius:9,marginBottom:12}}>Erro: {msg}</div>}
function useDados(tabelas,prefixo){
  const [dados,setDados]=useState({}),[loading,setLoading]=useState(true),[erro,setErro]=useState("");
  const recarregar=useCallback(async()=>{try{const vals=await Promise.all(tabelas.map(listar));setDados(Object.fromEntries(tabelas.map((t,i)=>[t,vals[i]||[]])));setErro("")}catch(e){setErro(e.message||String(e))}finally{setLoading(false)}},[tabelas.join("|")]);
  useEffect(()=>{recarregar();const ch=sb.channel(prefixo+"-realtime");tabelas.forEach(t=>ch.on("postgres_changes",{event:"*",schema:"public",table:t},recarregar));ch.subscribe();return()=>{try{sb.removeChannel(ch)}catch(e){}}},[recarregar]);
  return {dados,loading,erro,recarregar,setErro};
}
function Shell({titulo,eyebrow,tabs,tab,setTab,onSair,children}){return <div style={{minHeight:"100vh",paddingBottom:60}}><Header titulo={titulo} eyebrow={eyebrow} tabs={tabs} tab={tab} setTab={setTab} onSair={onSair}/><main style={{maxWidth:1080,margin:"0 auto",padding:"0 20px"}}>{children}</main></div>}

const TPLUV=["pluv_pontos","pluv_leituras"];
export function Pluviometria({onSair,nome}){
  const [tab,setTab]=useState("leituras");const {dados,loading,erro,recarregar,setErro}=useDados(TPLUV,"pluv");
  const pontos=dados.pluv_pontos||[], leituras=dados.pluv_leituras||[], mapa=Object.fromEntries(pontos.map(x=>[x.id,x]));
  if(loading)return <Centro txt="Carregando pluviometria…"/>;
  const salvarPonto=async(f,el)=>{try{await inserir("pluv_pontos",{nome:f.get("nome"),codigo:f.get("codigo"),localizacao:f.get("localizacao"),latitude:f.get("latitude")||null,longitude:f.get("longitude")||null,ativo:true});el.reset();recarregar()}catch(e){setErro(e.message)}};
  const salvarLeitura=async(f,el)=>{try{await inserir("pluv_leituras",{ponto_id:f.get("ponto_id"),data:f.get("data"),hora:f.get("hora")||null,precipitacao_mm:Number(f.get("precipitacao_mm")),responsavel:nome,observacao:f.get("observacao")});el.reset();recarregar()}catch(e){setErro(e.message)}};
  const total=leituras.reduce((s,x)=>s+Number(x.precipitacao_mm||0),0),max=leituras.reduce((m,x)=>Math.max(m,Number(x.precipitacao_mm||0)),0);
  return <Shell titulo="Pluviometria" eyebrow="Sementes Veneza · Medição pluviométrica" tabs={[["leituras","Medições"],["pontos","Pontos"],["relatorios","Relatórios"]]} tab={tab} setTab={setTab} onSair={onSair}><Erro msg={erro}/>
    {tab==="leituras"&&<><SectionTitle>Nova medição</SectionTitle><Form onSubmit={salvarLeitura}><Campo label="Ponto"><select name="ponto_id" required style={S.input}><option value="">Selecione</option>{pontos.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nome}</option>)}</select></Campo><Campo label="Data"><input name="data" type="date" required defaultValue={hoje()} style={S.input}/></Campo><Campo label="Hora"><input name="hora" type="time" style={S.input}/></Campo><Campo label="Precipitação (mm)"><input name="precipitacao_mm" type="number" min="0" step=".1" required style={S.input}/></Campo><Campo label="Observação"><input name="observacao" style={S.input}/></Campo></Form><SectionTitle>Histórico</SectionTitle><Tabela rows={leituras} cols={[["data","Data"],["ponto","Ponto",x=>mapa[x.ponto_id]?.nome||"—"],["precipitacao_mm","Chuva",x=>num(x.precipitacao_mm)+" mm"],["responsavel","Responsável"],["observacao","Observação"]]}/></>}
    {tab==="pontos"&&<><SectionTitle>Novo ponto</SectionTitle><Form onSubmit={salvarPonto}><Campo label="Código"><input name="codigo" required style={S.input}/></Campo><Campo label="Nome"><input name="nome" required style={S.input}/></Campo><Campo label="Localização"><input name="localizacao" style={S.input}/></Campo><Campo label="Latitude"><input name="latitude" type="number" step="any" style={S.input}/></Campo><Campo label="Longitude"><input name="longitude" type="number" step="any" style={S.input}/></Campo></Form><SectionTitle>Pontos cadastrados</SectionTitle><Tabela rows={pontos} cols={[["codigo","Código"],["nome","Nome"],["localizacao","Localização"],["latitude","Latitude"],["longitude","Longitude"],["ativo","Status",x=>x.ativo?"Ativo":"Inativo"]]}/></>}
    {tab==="relatorios"&&<><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Stat rotulo="Chuva acumulada" valor={num(total)+" mm"}/><Stat rotulo="Maior medição" valor={num(max)+" mm"}/><Stat rotulo="Medições" valor={leituras.length}/><Stat rotulo="Pontos ativos" valor={pontos.filter(x=>x.ativo).length}/></div><SectionTitle>Exportação</SectionTitle><button style={S.btn} onClick={()=>csv("pluviometria.csv",[["Data","Ponto","mm","Responsável","Observação"],...leituras.map(x=>[x.data,mapa[x.ponto_id]?.nome,x.precipitacao_mm,x.responsavel,x.observacao])])}>Baixar CSV</button></>}
  </Shell>
}

const TCOMB=["comb_veiculos","comb_tanques","comb_abastecimentos"];
export function Abastecimento({onSair,nome}){
  const [tab,setTab]=useState("abastecimentos");const {dados,loading,erro,recarregar,setErro}=useDados(TCOMB,"comb");
  const veiculos=dados.comb_veiculos||[],tanques=dados.comb_tanques||[],abs=dados.comb_abastecimentos||[],vm=Object.fromEntries(veiculos.map(x=>[x.id,x])),tm=Object.fromEntries(tanques.map(x=>[x.id,x]));
  if(loading)return <Centro txt="Carregando abastecimentos…"/>;
  const addVeiculo=async(f,e)=>{try{await inserir("comb_veiculos",{identificacao:f.get("identificacao"),placa:f.get("placa"),tipo:f.get("tipo"),combustivel:f.get("combustivel"),ativo:true});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const addTanque=async(f,e)=>{try{await inserir("comb_tanques",{nome:f.get("nome"),combustivel:f.get("combustivel"),capacidade_l:Number(f.get("capacidade_l")),saldo_l:Number(f.get("saldo_l")||0),ativo:true});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const addAbs=async(f,e)=>{try{await inserir("comb_abastecimentos",{veiculo_id:f.get("veiculo_id")||null,tanque_id:f.get("tanque_id")||null,data:f.get("data"),combustivel:f.get("combustivel"),litros:Number(f.get("litros")),valor:Number(f.get("valor")||0),odometro:Number(f.get("odometro")||0),posto:f.get("posto"),motorista:f.get("motorista")||nome,observacao:f.get("observacao")});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const litros=abs.reduce((s,x)=>s+Number(x.litros||0),0),valor=abs.reduce((s,x)=>s+Number(x.valor||0),0);
  return <Shell titulo="Abastecimento" eyebrow="Sementes Veneza · Combustíveis" tabs={[["abastecimentos","Abastecimentos"],["veiculos","Veículos"],["tanques","Tanques"],["relatorios","Relatórios"]]} tab={tab} setTab={setTab} onSair={onSair}><Erro msg={erro}/>
    {tab==="abastecimentos"&&<><SectionTitle>Novo abastecimento</SectionTitle><Form onSubmit={addAbs}><Campo label="Veículo"><select name="veiculo_id" style={S.input}><option value="">Sem veículo</option>{veiculos.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.identificacao}{x.placa?" · "+x.placa:""}</option>)}</select></Campo><Campo label="Tanque"><select name="tanque_id" style={S.input}><option value="">Posto externo</option>{tanques.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></Campo><Campo label="Data"><input name="data" type="date" required defaultValue={hoje()} style={S.input}/></Campo><Campo label="Combustível"><select name="combustivel" style={S.input}><option>Diesel</option><option>Gasolina</option><option>Etanol</option></select></Campo><Campo label="Litros"><input name="litros" type="number" min=".01" step=".01" required style={S.input}/></Campo><Campo label="Valor total"><input name="valor" type="number" min="0" step=".01" style={S.input}/></Campo><Campo label="Odômetro/Horímetro"><input name="odometro" type="number" min="0" step=".1" style={S.input}/></Campo><Campo label="Motorista"><input name="motorista" defaultValue={nome} style={S.input}/></Campo><Campo label="Posto"><input name="posto" style={S.input}/></Campo><Campo label="Observação"><input name="observacao" style={S.input}/></Campo></Form><SectionTitle>Histórico</SectionTitle><Tabela rows={abs} cols={[["data","Data"],["veiculo","Veículo",x=>vm[x.veiculo_id]?.identificacao||"—"],["tanque","Origem",x=>tm[x.tanque_id]?.nome||x.posto||"Externo"],["litros","Litros",x=>num(x.litros)],["valor","Valor",x=>brl(x.valor)],["motorista","Motorista"]]}/></>}
    {tab==="veiculos"&&<><SectionTitle>Novo veículo/equipamento</SectionTitle><Form onSubmit={addVeiculo}><Campo label="Identificação"><input name="identificacao" required style={S.input}/></Campo><Campo label="Placa"><input name="placa" style={S.input}/></Campo><Campo label="Tipo"><input name="tipo" placeholder="Caminhão, trator…" style={S.input}/></Campo><Campo label="Combustível"><select name="combustivel" style={S.input}><option>Diesel</option><option>Gasolina</option><option>Etanol</option></select></Campo></Form><SectionTitle>Frota</SectionTitle><Tabela rows={veiculos} cols={[["identificacao","Identificação"],["placa","Placa"],["tipo","Tipo"],["combustivel","Combustível"],["ativo","Status",x=>x.ativo?"Ativo":"Inativo"]]}/></>}
    {tab==="tanques"&&<><SectionTitle>Novo tanque</SectionTitle><Form onSubmit={addTanque}><Campo label="Nome"><input name="nome" required style={S.input}/></Campo><Campo label="Combustível"><select name="combustivel" style={S.input}><option>Diesel</option><option>Gasolina</option><option>Etanol</option></select></Campo><Campo label="Capacidade (L)"><input name="capacidade_l" type="number" min="0" required style={S.input}/></Campo><Campo label="Saldo inicial (L)"><input name="saldo_l" type="number" min="0" style={S.input}/></Campo></Form><SectionTitle>Tanques</SectionTitle><Tabela rows={tanques} cols={[["nome","Nome"],["combustivel","Combustível"],["capacidade_l","Capacidade",x=>num(x.capacidade_l)+" L"],["saldo_l","Saldo",x=>num(x.saldo_l)+" L"],["nivel","Nível",x=>x.capacidade_l?Math.round(x.saldo_l/x.capacidade_l*100)+"%":"—"]]}/></>}
    {tab==="relatorios"&&<><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Stat rotulo="Volume abastecido" valor={num(litros)+" L"}/><Stat rotulo="Valor total" valor={brl(valor)}/><Stat rotulo="Custo médio" valor={litros?brl(valor/litros)+"/L":"—"}/><Stat rotulo="Lançamentos" valor={abs.length}/></div><SectionTitle>Exportação</SectionTitle><button style={S.btn} onClick={()=>csv("abastecimentos.csv",[["Data","Veículo","Origem","Combustível","Litros","Valor","Odômetro","Motorista"],...abs.map(x=>[x.data,vm[x.veiculo_id]?.identificacao,tm[x.tanque_id]?.nome||x.posto,x.combustivel,x.litros,x.valor,x.odometro,x.motorista])])}>Baixar CSV</button></>}
  </Shell>
}

const TALM=["alm_itens","alm_movimentacoes","alm_inventarios","alm_inventario_itens"];
export function Almoxarifado({onSair,nome}){
  const [tab,setTab]=useState("movimentacoes");const {dados,loading,erro,recarregar,setErro}=useDados(TALM,"alm");
  const itens=dados.alm_itens||[],movs=dados.alm_movimentacoes||[],invs=dados.alm_inventarios||[],conts=dados.alm_inventario_itens||[],im=Object.fromEntries(itens.map(x=>[x.id,x]));
  if(loading)return <Centro txt="Carregando almoxarifado…"/>;
  const saldo=id=>movs.filter(x=>x.item_id===id).reduce((s,x)=>s+(x.tipo==="entrada"?1:-1)*Number(x.quantidade||0),0);
  const addItem=async(f,e)=>{try{await inserir("alm_itens",{codigo:f.get("codigo"),nome:f.get("nome"),categoria:f.get("categoria"),unidade:f.get("unidade"),estoque_minimo:Number(f.get("estoque_minimo")||0),localizacao:f.get("localizacao"),ativo:true});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const addMov=async(f,e)=>{try{await inserir("alm_movimentacoes",{item_id:f.get("item_id"),data:f.get("data"),tipo:f.get("tipo"),quantidade:Number(f.get("quantidade")),valor_unitario:Number(f.get("valor_unitario")||0),documento:f.get("documento"),responsavel:f.get("responsavel")||nome,observacao:f.get("observacao"),origem:f.get("origem")});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const abrirInv=async(f,e)=>{try{const inv=await inserir("alm_inventarios",{data:f.get("data"),status:"aberto",responsavel:f.get("responsavel")||nome,observacao:f.get("observacao")});if(itens.length)await ok(sb.from("alm_inventario_itens").insert(itens.filter(x=>x.ativo).map(x=>({inventario_id:inv.id,item_id:x.id,saldo_sistema:saldo(x.id),contagem_fisica:saldo(x.id),diferenca:0}))));e.reset();recarregar()}catch(x){setErro(x.message)}};
  const total=itens.reduce((s,x)=>s+saldo(x.id),0),baixos=itens.filter(x=>saldo(x.id)<Number(x.estoque_minimo||0));
  return <Shell titulo="Almoxarifado" eyebrow="Sementes Veneza · Estoque" tabs={[["movimentacoes","Movimentações"],["itens","Itens"],["inventarios","Inventários"],["relatorios","Relatórios"]]} tab={tab} setTab={setTab} onSair={onSair}><Erro msg={erro}/>
    {tab==="movimentacoes"&&<><SectionTitle>Nova movimentação</SectionTitle><Form onSubmit={addMov}><Campo label="Item"><select name="item_id" required style={S.input}><option value="">Selecione</option>{itens.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nome}</option>)}</select></Campo><Campo label="Data"><input name="data" type="date" required defaultValue={hoje()} style={S.input}/></Campo><Campo label="Tipo"><select name="tipo" style={S.input}><option value="entrada">Entrada</option><option value="saida">Saída</option></select></Campo><Campo label="Quantidade"><input name="quantidade" type="number" min=".001" step=".001" required style={S.input}/></Campo><Campo label="Valor unitário"><input name="valor_unitario" type="number" min="0" step=".01" style={S.input}/></Campo><Campo label="Documento"><input name="documento" style={S.input}/></Campo><Campo label="Origem/destino"><input name="origem" style={S.input}/></Campo><Campo label="Responsável"><input name="responsavel" defaultValue={nome} style={S.input}/></Campo><Campo label="Observação"><input name="observacao" style={S.input}/></Campo></Form><SectionTitle>Histórico</SectionTitle><Tabela rows={movs} cols={[["data","Data"],["item","Item",x=>im[x.item_id]?.nome||"—"],["tipo","Tipo"],["quantidade","Quantidade",x=>num(x.quantidade)+" "+(im[x.item_id]?.unidade||"")],["valor_unitario","Valor unit.",x=>brl(x.valor_unitario)],["responsavel","Responsável"]]}/></>}
    {tab==="itens"&&<><SectionTitle>Novo item</SectionTitle><Form onSubmit={addItem}><Campo label="Código"><input name="codigo" required style={S.input}/></Campo><Campo label="Nome"><input name="nome" required style={S.input}/></Campo><Campo label="Categoria"><input name="categoria" style={S.input}/></Campo><Campo label="Unidade"><select name="unidade" style={S.input}><option>un</option><option>kg</option><option>L</option><option>m</option><option>cx</option></select></Campo><Campo label="Estoque mínimo"><input name="estoque_minimo" type="number" min="0" step=".001" style={S.input}/></Campo><Campo label="Localização"><input name="localizacao" style={S.input}/></Campo></Form><SectionTitle>Estoque atual</SectionTitle><Tabela rows={itens} cols={[["codigo","Código"],["nome","Item"],["categoria","Categoria"],["localizacao","Localização"],["saldo","Saldo",x=><b style={{color:saldo(x.id)<Number(x.estoque_minimo||0)?C.clay:C.ink}}>{num(saldo(x.id))} {x.unidade}</b>],["estoque_minimo","Mínimo",x=>num(x.estoque_minimo)+" "+x.unidade]]}/></>}
    {tab==="inventarios"&&<><SectionTitle>Novo inventário</SectionTitle><Form onSubmit={abrirInv} label="Abrir inventário"><Campo label="Data"><input name="data" type="date" required defaultValue={hoje()} style={S.input}/></Campo><Campo label="Responsável"><input name="responsavel" defaultValue={nome} style={S.input}/></Campo><Campo label="Observação"><input name="observacao" style={S.input}/></Campo></Form><SectionTitle>Inventários</SectionTitle><Tabela rows={invs} cols={[["data","Data"],["status","Status"],["responsavel","Responsável"],["itens","Itens",x=>conts.filter(c=>c.inventario_id===x.id).length],["observacao","Observação"]]}/></>}
    {tab==="relatorios"&&<><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Stat rotulo="Itens cadastrados" valor={itens.length}/><Stat rotulo="Saldo total" valor={num(total)}/><Stat rotulo="Abaixo do mínimo" valor={baixos.length}/><Stat rotulo="Movimentações" valor={movs.length}/></div><SectionTitle>Itens abaixo do mínimo</SectionTitle><Tabela rows={baixos} cols={[["codigo","Código"],["nome","Item"],["saldo","Saldo",x=>num(saldo(x.id))+" "+x.unidade],["estoque_minimo","Mínimo",x=>num(x.estoque_minimo)+" "+x.unidade]]}/><SectionTitle>Exportação</SectionTitle><button style={S.btn} onClick={()=>csv("estoque.csv",[["Código","Item","Categoria","Unidade","Saldo","Mínimo","Localização"],...itens.map(x=>[x.codigo,x.nome,x.categoria,x.unidade,saldo(x.id),x.estoque_minimo,x.localizacao])])}>Baixar CSV</button></>}
  </Shell>
}
